apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/argocon2022-workshop/demo-app
  newName: ghcr.io/jtmilan/demo-app
  newTag: 575176d4353b445fe1189d64bfc380483e47131d
